### ISSUE TITLE
Show diff between expected and actual output

### ISSUE THREAD

**Issue by segeljakt** [jfecher/golden-tests#3]
I got this goldentest:
```
c = true
x = 3
if c
  then x
  else x

# expected stdout:
# c: bool = true
# x: i32 = 3
# x2: i32 = if c
#   then
#     x
#   else
#     x
# x2
```
This is the output when running manually:
```
09:08:29 cargo run if.arc
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `/home/klas/Workspace/arc/arc-script/target/debug/arc-script if.arc`

c: bool = true
x: i32 = 3
x2: i32 = if c
  then
    x
  else
    x
x2
```
This is what goldentests prints:
```
test run_golden_tests ... FAILED

failures:

---- run_golden_tests stdout ----

tests/goldentests/if.arc: Actual stdout differs from expected stdout:
  1| c: bool = true
  2| x: i32 = 3
  3| x2: i32 = if c
  4|   then
  5|     x
  6|   else
  7|     x
  8| x2
```
Goldentests says there is a difference but I have trouble spotting it. It looks like the manual run prints a newline at the start, but goldentests does not. Would it be possible for goldentests to print the difference, maybe using https://docs.rs/text-diff/0.4.0/text_diff/ or some similar crate?

**Comment by segeljakt** [comment]
In the README, I see now that it is supposed to print the difference, I feel like I'm doing something wrong 😓

**Comment by segeljakt** [comment]
Now I realized, I forgot to specify that there should be a space after the comment character.

**Comment by segeljakt** [comment]
This is the error:
![image](https://user-images.githubusercontent.com/15143039/89385579-1e818d00-d700-11ea-9cc3-ee4b0d1769cf.png)

**Comment by jfecher** [comment]
Hi, sorry I missed this. Just want to follow up: were you confused by the extra trailing space not being clear enough diff formatting in your screenshot? Or were you using an older version of goldentests originally without the trailing space highlighting (that was recently added in 0.3.6)?

If you were confused by the output originally I'm open to suggestions for improvements as well :)

**Comment by segeljakt** [comment]
Hey, no problem. The problem was completely me. It was that I wrote:
```
let config = TestConfig::new("target/debug/my-binary", "my-test-path", "#")?;
```
instead of:
```
let config = TestConfig::new("target/debug/my-binary", "my-test-path", "# ")?;
```

**Comment by jfecher** [comment]
Ah, that'll do it. I think if I make it so that if at least one of "expected stdout:" or "expected stderr:" wasn't found then an appropriate warning is issued that will hopefully reduce this issue for new users in the future
